Update run

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,16 +1,8 @@
 #!/bin/bash 
 
-#    ▀█████████▄   ▄██████▄     ▄████████    ▄████████
-#      ███    ███ ███    ███   ███    ███   ███    ███
-#      ███    ███ ███    ███   ███    █▀    ███    █▀
-#     ▄███▄▄▄██▀  ███    ███   ███          ███
-#    ▀▀███▀▀▀██▄  ███    ███ ▀███████████ ▀███████████ ¦ Dev : @TH3BOSS
-#      ███    ██▄ ███    ███          ███          ███ ¦ Dev : @OMMMM
-#      ███    ███ ███    ███    ▄█    ███    ▄█    ███
-#    ▄█████████▀   ▀██████▀   ▄████████▀   ▄████████▀  ¦ Source TH3BOSS BY @TH3BS
 
-#---------------------------------------------------------------------
 cd $(cd $(dirname $0); pwd)
+ 
 RED='\033[0;31m'
 SMAY='\033[0;36m' 
 GREEN='\033[0;32m'
@@ -21,18 +13,35 @@ WHITEC='\033[01;91m'
 CNIL='\033[0m'
 Version=`lsb_release -rs | cut -f1 -d"."`
 
+if [ "$Version" == "18" ];then
+echo -e "${GREEN}
+/$$$$$$  /$$$$$$$$  /$$$$$$  /$$$$$$$ 
+ /$$__  $$|_____ $$  /$$__  $$| $$__  $$
+| $$  \__/     /$$/ | $$  \ $$| $$  \ $$
+| $$          /$$/  | $$$$$$$$| $$$$$$$/
+| $$         /$$/   | $$__  $$| $$__  $$
+| $$    $$  /$$/    | $$  | $$| $$  \ $$
+|  $$$$$$/ /$$$$$$$$| $$  | $$| $$  | $$
+ \______/ |________/|__/  |__/|__/  |__/
+----------------------------------------------------------------------${CNIL}"
+echo -e "${RED}| للاسف لايمكنك تنصيب السورس ع نظام اوبنتو {${Version}} يجب ان يكون على اصدار  اقل مثلا  ${SMAY}14 او 16
+${CNIL}";
+echo -e "${RED}| Sorry Canot install Source on Ubuntu {${Version}} Please install system To Ubuntu ${SMAY}14 or 16 ${RED} For Run The Source CZAR 
+${CNIL}";
+exit;
+fi
+
 
 if [ ! -f "./TG" ]; then
 echo -e "${RED}
 ¦
 ¦ CAUTION:${WHITB} Your Not Dwonload TG .
-¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Source TH3BOSS${CNIL} . \n
+¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Source CZAR${CNIL} . \n
 \n\n"
 chmod +x ./ins
 ./ins
 exit;
 fi
-
 
 if [ ! -f "./inc/Token.txt" ]; then
 echo -e "${RED}
@@ -42,36 +51,23 @@ echo -e "${RED}
 \n\n"
 lua ./inc/Run.lua
 exit;
-else
+fi
+
+
 TOKEN=`cat ./inc/Token.txt`
-BOTID=`echo $TOKEN | cut -f1 -d":"`
-Sudo=$(redis-cli get ${BOTID}:SUDO_ID:)
-if [[ $Sudo == "" ]]; then
-rm -fr ./inc/Token.txt
-lua ./inc/Run.lua
-exit;
-fi
-fi
+sudo chmod +x ./TG
 
-UserBot=$(redis-cli get ${BOTID}:UserNameBot:)
-
-echo "$Sudo"
-echo "$UserBot"
-
-chmod +x ./TG  
-
-if [ "$1" == "R" ]; then
-while true; do
-sleep 1s
-rm -fr ./BOSS
-sudo rm -fr ~/.telegram-cli
-./TG -s ./inc/Run.lua --bot=$TOKEN
+if [ "$1" == "R" ] ; then
+while(true) do
+killall -q ./TG
+sudo rm -fr ../.telegram-cli
+./TG -s inc/Run.lua --bot=$TOKEN
 done
-else 
-if ! screen -list | grep -q "$UserBot"; then
-screen -S "$UserBot" ./run R
 else
-screen -X -S "$UserBot" quit
-screen -S "$UserBot" ./run R
+
+if ! screen -list | grep -q "CZAR"; then
+screen -S BOSS ./run R
 fi
+screen -S BOSS -X kill
+screen -S BOSS ./run R
 fi
